import React from 'react'
import ReactDOM from 'react-dom'
import './index.css'

import App from './component/App'
// import App from './props/App'
// import App from './no-jsx/App'
// import App from './class/App'
// import App from './state/App'
// import App from './events/App'
// import App from './upflow/App'
// import App from './refs/App'
// import App from './composition/App'
// import App from './render-props/App'
// import App from './function-as-children/App'
// import App from './render-props-advanced/App'
// import App from './function-as-children-advanced/App'
// import App from './hoc/App'
// import App from './hoc-advanced/App'
// import App from './context-api/App'
// import App from './context-type/App'

ReactDOM.render(<App />, document.getElementById('root'))
